DROP database ista_website_db;

-- MySQL Script generated by MySQL Workbench
-- Wed May 31 15:36:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ista_website_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ista_website_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ista_website_db` DEFAULT CHARACTER SET utf8 ;
USE `ista_website_db` ;

-- -----------------------------------------------------
-- Table `ista_website_db`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ista_website_db`.`article` (
  `article_id` INT NOT NULL AUTO_INCREMENT,
  `publisher_id` INT NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `body` VARCHAR(10000) NULL,
  `date_time` DATETIME NOT NULL,
  `keywords` VARCHAR(200) NOT NULL,
  `resources` INT NULL,
  `user_type` VARCHAR(20) NOT NULL DEFAULT 0,
  `key_img_path` VARCHAR(500) NOT NULL DEFAULT '/resources/img/articles/default_article_img.jpg',
  PRIMARY KEY (`article_id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ista_website_db`.`article_resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ista_website_db`.`article_resources` (
  `resource_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL DEFAULT 'image',
  `path` VARCHAR(500) NOT NULL DEFAULT 0,
  `article_id` INT NULL,
  PRIMARY KEY (`resource_id`),
  UNIQUE INDEX `path_UNIQUE` (`path` ASC) ,
  UNIQUE INDEX `resource_id_UNIQUE` (`resource_id` ASC) ,
  INDEX `fk_resources_article_idx` (`article_id` ASC) ,
  CONSTRAINT `fk_resources_article`
    FOREIGN KEY (`article_id`)
    REFERENCES `ista_website_db`.`article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ista_website_db`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ista_website_db`.`class` (
  `class_id` INT NOT NULL AUTO_INCREMENT,
  `emploi` JSON NULL,
  `class_year` DATE NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `is_current` TINYINT NOT NULL DEFAULT 1,
  `emploi_pdf_path` VARCHAR(500) NOT NULL DEFAULT '/resources/pdf/emploi_du_temps/emploi_placeholder.pdf',
  PRIMARY KEY (`class_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ista_website_db`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ista_website_db`.`student` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(300) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `national_student_id` VARCHAR(45) NULL,
  `numberInClass` INT NULL,
  `is_publisher` INT NOT NULL DEFAULT 0,
  `is_responsable` INT NOT NULL DEFAULT 0,
  `photo_path` VARCHAR(500) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `phone_number` VARCHAR(15) NULL,
  `contact_email` VARCHAR(100) NULL,
  `class` INT NOT NULL,
  `birth_date` DATE NULL,
  PRIMARY KEY (`student_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`student_id` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `national_student_id_UNIQUE` (`national_student_id` ASC) ,
  UNIQUE INDEX `photo_path_UNIQUE` (`photo_path` ASC) ,
  INDEX `fk_student_class_idx` (`class` ASC) ,
  CONSTRAINT `fk_student_class`
    FOREIGN KEY (`class`)
    REFERENCES `ista_website_db`.`class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ista_website_db`.`super_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ista_website_db`.`super_user` (
  `super_user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(300) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `super_user_privelage` VARCHAR(45) NOT NULL,
  `super_user_legacy` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`super_user_id`),
  UNIQUE INDEX `super_user_id_UNIQUE` (`super_user_id` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `super_user_legacy_UNIQUE` (`super_user_legacy` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ista_website_db`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ista_website_db`.`teacher` (
  `teacher_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `photo_path` VARCHAR(500) NULL,
  `phone_number` VARCHAR(15) NULL,
  `contact_email` VARCHAR(100) NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`teacher_id`),
  UNIQUE INDEX `photo_path_UNIQUE` (`photo_path` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `contact_email_UNIQUE` (`contact_email` ASC) ,
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ista_website_db`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ista_website_db`.`subject` (
  `subject_id` INT NOT NULL AUTO_INCREMENT,
  `subject_name` VARCHAR(100) NOT NULL,
  `class_id` INT NOT NULL,
  `teacher_id` INT NOT NULL,
  INDEX `fk_subject_teacher_idx` (`teacher_id` ASC) ,
  PRIMARY KEY (`subject_id`),
  CONSTRAINT `fk_subject_class`
    FOREIGN KEY (`class_id`)
    REFERENCES `ista_website_db`.`class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subject_teacher`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `ista_website_db`.`teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ista_website_db`.`student_resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ista_website_db`.`student_resources` (
  `resource_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `title` VARCHAR(45) NOT NULL,
  `path` VARCHAR(45) NOT NULL,
  `student_id` INT NULL,
  `notifications` INT NULL,
  PRIMARY KEY (`resource_id`),
  UNIQUE INDEX `resource_id_UNIQUE` (`resource_id` ASC) ,
  INDEX `student_resources_student_idx` (`student_id` ASC) ,
  CONSTRAINT `student_resources_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `ista_website_db`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ista_website_db`.`note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ista_website_db`.`note` (
  `subject_id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `controle_1` INT NULL,
  `controle_2` INT NULL,
  `controle_3` INT NULL,
  `EFM` INT NULL,
  INDEX `note_subject_idx` (`subject_id` ASC) ,
  INDEX `note_student_idx` (`student_id` ASC) ,
  CONSTRAINT `note_subject`
    FOREIGN KEY (`subject_id`)
    REFERENCES `ista_website_db`.`subject` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `note_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `ista_website_db`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ista_website_db`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ista_website_db`.`notification` (
  `notification_id` INT NOT NULL AUTO_INCREMENT,
  `recepient` INT NOT NULL,
  `message` TEXT NULL,
  `checked` TINYINT NOT NULL DEFAULT 0,
  `context` VARCHAR(45) NOT NULL,
  `user_type` VARCHAR(25) NOT NULL,
  `link` TEXT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`notification_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ista_website_db`.`conversation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ista_website_db`.`conversation` (
  `conversation_id` INT NOT NULL AUTO_INCREMENT,
  `first_user_id` INT NULL,
  `second_user_id` INT NULL,
  `first_user_type` VARCHAR(45) NULL,
  `second_user_type` VARCHAR(45) NULL,
  PRIMARY KEY (`conversation_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ista_website_db`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ista_website_db`.`message` (
  `message_id` INT NOT NULL AUTO_INCREMENT,
  `sender_id` INT NOT NULL,
  `recepient_id` INT NOT NULL,
  `message` TEXT NOT NULL,
  `time` DATETIME NULL,
  `seen` TINYINT NOT NULL DEFAULT 0,
  `conversation_id` INT NOT NULL,
  PRIMARY KEY (`message_id`),
  INDEX `fk_message_conversation_idx` (`conversation_id` ASC) ,
  CONSTRAINT `fk_message_conversation`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `ista_website_db`.`conversation` (`conversation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ista_website_db`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ista_website_db`.`session` (
  `session_id` VARCHAR(100) NOT NULL,
  `user_id` INT NOT NULL,
  `user_type` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL,
  `data` JSON NOT NULL,
  PRIMARY KEY (`session_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ista_website_db`.`administration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ista_website_db`.`administration` (
  `administration_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `contact_email` VARCHAR(100) NULL,
  PRIMARY KEY (`administration_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ista_website_db`.`resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ista_website_db`.`resource` (
  `resource_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `path` VARCHAR(500) NULL,
  PRIMARY KEY (`resource_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ista_website_db`.`homework`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ista_website_db`.`homework` (
  `homework_id` INT NOT NULL AUTO_INCREMENT,
  `teacher_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `class_id` INT NOT NULL,
  `content` TEXT NOT NULL,
  `resource1_id` INT NULL,
  `resource2_id` INT NULL,
  `resource3_id` INT NULL,
  PRIMARY KEY (`homework_id`),
  INDEX `fk_homework_teacher_idx` (`teacher_id` ASC) ,
  INDEX `fk_homework_subject_idx` (`subject_id` ASC) ,
  INDEX `fk_homework_class_idx` (`class_id` ASC) ,
  INDEX `fk_homework_resource1_idx` (`resource1_id` ASC) ,
  INDEX `fk_homework_resource2_idx` (`resource2_id` ASC) ,
  INDEX `fk_homework_resource3_idx` (`resource3_id` ASC) ,
  CONSTRAINT `fk_homework_teacher`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `ista_website_db`.`teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_homework_subject`
    FOREIGN KEY (`subject_id`)
    REFERENCES `ista_website_db`.`subject` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_homework_class`
    FOREIGN KEY (`class_id`)
    REFERENCES `ista_website_db`.`class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_homework_resource1`
    FOREIGN KEY (`resource1_id`)
    REFERENCES `ista_website_db`.`resource` (`resource_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_homework_resource2`
    FOREIGN KEY (`resource2_id`)
    REFERENCES `ista_website_db`.`resource` (`resource_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_homework_resource3`
    FOREIGN KEY (`resource3_id`)
    REFERENCES `ista_website_db`.`resource` (`resource_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ista_website_db`.`announcement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ista_website_db`.`announcement` (
  `announcement_id` INT NOT NULL AUTO_INCREMENT,
  `text` MEDIUMTEXT NOT NULL,
  `date_time` DATETIME NULL,
  PRIMARY KEY (`announcement_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
